receivers:
 otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:55681"

extensions:
 health_check:
   endpoint: "0.0.0.0:13133"

exporters:
 zipkin:
   endpoint: "http://zipkin:9411/api/v2/spans"
 prometheus:
   endpoint: "0.0.0.0:9100"
 logging:
   loglevel: debug


service:
 extensions: [health_check]
 pipelines:
   traces:
     receivers: [otlp]
     exporters: [zipkin]
   metrics:
     receivers: [otlp]
     exporters: [prometheus, logging]